// <auto-generated />
namespace Chat.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DodajLoginFlag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DodajLoginFlag));
        
        string IMigrationMetadata.Id
        {
            get { return "202205281943554_DodajLoginFlag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
