// <auto-generated />
namespace Chat.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Primer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Primer));
        
        string IMigrationMetadata.Id
        {
            get { return "202205291220012_Primer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
